########################################################################################### 私有构建
# docker.io/jetbrains/teamcity-agent
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_jetbrains_teamcity-agent:/^(.*)(-n-ext)$/":
  - "docker-hosted.nstl-dev.com/jetbrains/elasticsearch"

# docker.io/elasticsearch
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_elasticsearch:/^(.*)(-n-ext)$/":
  - "docker-hosted.nstl-dev.com/library/elasticsearch"
