########################################################################################### 私有构建
# docker.io/jetbrains/teamcity-agent
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_jetbrains_teamcity-agent:/^(.*)(-n-ext)$/":
  - "docker-hosted.nstl-dev.com/jetbrains/elasticsearch"

# docker.io/elasticsearch
"registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_elasticsearch:/^(.*)(-n-ext)$/":
  - "docker-hosted.nstl-dev.com/library/elasticsearch"

########################################################################################### docker.io/consul
# docker.io/consul
# Tag list: https://explore.ggcr.dev/?repo=consul
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_consul:/^(1.11)(.[0-9]+)*(-rc[0-9]*)?$/:
  - docker-hosted.nstl-dev.com/library/consul
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_consul:/^(1.15)(.[0-9]+)*(-rc[0-9]*)?$/:
  - docker-hosted.nstl-dev.com/library/consul

########################################################################################### docker.io/adoptopenjdk
# docker.io/adoptopenjdk/openjdk11
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_adoptopenjdk_openjdk11:latest:
  - docker-hosted.nstl-dev.com/adoptopenjdk/openjdk11
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_adoptopenjdk_openjdk11:debian:
  - docker-hosted.nstl-dev.com/adoptopenjdk/openjdk11

########################################################################################### docker.io/eclipse-temurin
# docker.io/eclipse-temurin 11
# Tag list: https://explore.ggcr.dev/?repo=eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:11,11-alpine,11-centos7,11-focal,11-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:11-jdk,11-jdk-alpine,11-jdk-centos7,11-jdk-focal,11-jdk-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:11-jre,11-jre-alpine,11-jre-centos7,11-jre-focal,11-jre-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin

# docker.io/eclipse-temurin 17
# Tag list: https://explore.ggcr.dev/?repo=eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:17,17-alpine,17-centos7,17-focal,17-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:17-jdk,17-jdk-alpine,17-jdk-centos7,17-jdk-focal,17-jdk-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:17-jre,17-jre-alpine,17-jre-centos7,17-jre-focal,17-jre-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin

# docker.io/eclipse-temurin 21
# Tag list: https://explore.ggcr.dev/?repo=eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:21,21-alpine,21-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:21-jdk,21-jdk-alpine,21-jdk-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_eclipse-temurin:21-jre,21-jre-alpine,21-jre-jammy:
  - docker-hosted.nstl-dev.com/library/eclipse-temurin

########################################################################################### docker.io/jetbrains
# docker.io/jetbrains/teamcity-server
# Tag list: https://explore.ggcr.dev/?repo=jetbrains/teamcity-server
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_jetbrains_teamcity-server:/^(2024|2025|2026)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/jetbrains/teamcity-server

# docker.io/jetbrains/teamcity-agent
# Tag list: https://explore.ggcr.dev/?repo=jetbrains/teamcity-agent
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_jetbrains_teamcity-agent:/^(2024|2025|2026)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/jetbrains/teamcity-agent

########################################################################################### docker.io/nginx
# docker.io/nginx
# Tag list: https://explore.ggcr.dev/?repo=nginx
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_nginx:/stable.*/:
  - docker-hosted.nstl-dev.com/library/nginx
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_nginx:latest:
  - docker-hosted.nstl-dev.com/library/nginx

########################################################################################### docker.io/openresty
# docker.io/openresty/openresty
# Tag list: https://explore.ggcr.dev/?repo=openresty/openresty
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_openresty_openresty:/latest.*/:
  - docker-hosted.nstl-dev.com/openresty/openresty
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_openresty_openresty:alpine,bionic,bookworm,bullseye,buster,centos,fedora,focal,jammy,jessie,rocky,stretch,trusty,wheezy,xenial:
  - docker-hosted.nstl-dev.com/openresty/openresty

########################################################################################### docker.io/elasticsearch
# docker.io/elasticsearch
# Tag list: https://explore.ggcr.dev/?repo=elasticsearch
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/elasticsearch/elasticsearch
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_elasticsearch:7.6.2:
  - docker-hosted.nstl-dev.com/library/elasticsearch
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_elasticsearch:7.10.2:
  - docker-hosted.nstl-dev.com/library/elasticsearch
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_elasticsearch:7.17.22:
  - docker-hosted.nstl-dev.com/library/elasticsearch
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_elasticsearch:8.14.1:
  - docker-hosted.nstl-dev.com/library/elasticsearch

########################################################################################### docker.io/logstash
# docker.io/logstash
# Tag list: https://explore.ggcr.dev/?repo=logstash
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/logstash/logstash
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_logstash:7.6.2:
  - docker-hosted.nstl-dev.com/library/logstash
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_logstash:7.10.2:
  - docker-hosted.nstl-dev.com/library/logstash
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_logstash:7.17.22:
  - docker-hosted.nstl-dev.com/library/logstash
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_logstash:8.14.1:
  - docker-hosted.nstl-dev.com/library/logstash

########################################################################################### docker.io/kibana
# docker.io/kibana
# Tag list: https://explore.ggcr.dev/?repo=kibana
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/kibana/kibana
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_kibana:7.6.2:
  - docker-hosted.nstl-dev.com/library/kibana
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_kibana:7.10.2:
  - docker-hosted.nstl-dev.com/library/kibana
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_kibana:7.17.22:
  - docker-hosted.nstl-dev.com/library/kibana
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_kibana:8.14.1:
  - docker-hosted.nstl-dev.com/library/kibana
########################################################################################### filebeat 官方没有, 风格模仿
# docker.io/kibana
# Tag list: https://explore.ggcr.dev/?repo=docker.elastic.co/beats/filebeat
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_filebeat:7.6.2:
  - docker-hosted.nstl-dev.com/library/filebeat
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_filebeat:7.10.2:
  - docker-hosted.nstl-dev.com/library/filebeat
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_filebeat:7.17.22:
  - docker-hosted.nstl-dev.com/library/filebeat
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_filebeat:8.14.1:
  - docker-hosted.nstl-dev.com/library/filebeat

########################################################################################### kubernetes
########################################################################################### registry.k8s.io/kube-apiserver
# registry.k8s.io/kube-apiserver
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-apiserver
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-apiserver:/^(v1.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-apiserver
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-apiserver:/^(v1.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-apiserver
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-apiserver:/^(v1.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-apiserver
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-apiserver:/^(v1.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-apiserver
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-apiserver:/^(v1.29)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-apiserver
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-apiserver:/^(v1.30)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-apiserver

########################################################################################### registry.k8s.io/kube-controller-manager
# registry.k8s.io/kube-controller-manager
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-controller-manager
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-controller-manager:/^(v1.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-controller-manager
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-controller-manager:/^(v1.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-controller-manager
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-controller-manager:/^(v1.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-controller-manager
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-controller-manager:/^(v1.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-controller-manager
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-controller-manager:/^(v1.29)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-controller-manager
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-controller-manager:/^(v1.30)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-controller-manager

########################################################################################### registry.k8s.io/kube-scheduler
# registry.k8s.io/kube-scheduler
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-scheduler
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-scheduler:/^(v1.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-scheduler
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-scheduler:/^(v1.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-scheduler
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-scheduler:/^(v1.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-scheduler
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-scheduler:/^(v1.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-scheduler
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-scheduler:/^(v1.29)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-scheduler
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-scheduler:/^(v1.30)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-scheduler

########################################################################################### registry.k8s.io/kube-proxy
# registry.k8s.io/kube-proxy
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/kube-proxy
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-proxy:/^(v1.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-proxy
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-proxy:/^(v1.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-proxy
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-proxy:/^(v1.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-proxy
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-proxy:/^(v1.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-proxy
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-proxy:/^(v1.29)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-proxy
registry.cn-beijing.aliyuncs.com/nstl_google_containers/kube-proxy:/^(v1.30)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/kube-proxy

########################################################################################### registry.k8s.io/coredns/coredns
# registry.k8s.io/coredns/coredns
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/coredns/coredns
registry.cn-beijing.aliyuncs.com/nstl_google_containers/coredns:/^v([0-9]+)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/coredns

########################################################################################### registry.k8s.io/pause
# registry.k8s.io/pause
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/pause
registry.cn-beijing.aliyuncs.com/nstl_google_containers/pause:/^([0-9]+)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/google_containers/pause

########################################################################################### registry.k8s.io/etcd
# registry.k8s.io/etcd
# Tag list: https://explore.ggcr.dev/?repo=registry.k8s.io/etcd
registry.cn-beijing.aliyuncs.com/nstl_google_containers/etcd:/^(3)(.[0-9]+)*(-[0-9]+)?$/:
  - docker-hosted.nstl-dev.com/google_containers/etcd

########################################################################################### docker.io/calico/kube-controllers
# docker.io/calico/kube-controllers
# Tag list: https://explore.ggcr.dev/?repo=calico/kube-controllers
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_kube-controllers:/^(v3.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/kube-controllers
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_kube-controllers:/^(v3.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/kube-controllers
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_kube-controllers:/^(v3.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/kube-controllers
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_kube-controllers:/^(v3.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/kube-controllers

########################################################################################### docker.io/calico/cni
# docker.io/calico/cni
# Tag list: https://explore.ggcr.dev/?repo=calico/cni
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_cni:/^(v3.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/cni
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_cni:/^(v3.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/cni
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_cni:/^(v3.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/cni
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_cni:/^(v3.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/cni

########################################################################################### docker.io/calico/node
# docker.io/calico/node
# Tag list: https://explore.ggcr.dev/?repo=calico/node
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_node:/^(v3.25)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/node
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_node:/^(v3.26)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/node
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_node:/^(v3.27)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/node
registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_calico_node:/^(v3.28)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/calico/node

########################################################################################### ghcr.io/kube-vip/kube-vip
# ghcr.io/kube-vip/kube-vip
# Tag list: https://explore.ggcr.dev/?repo=ghcr.io/kube-vip/kube-vip
registry.cn-beijing.aliyuncs.com/public-image-mirror/ghcr.io_kube-vip_kube-vip:/^v([0-9]+)(.[0-9]+)*$/:
  - docker-hosted.nstl-dev.com/ghcr.io/kube-vip/kube-vip