public:
  # 官方镜像
  - origin: docker.io/library/consul
    transfer: registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_library_consul
    private: docker-hosted.nstl-dev.com/library/consul
  # 机构镜像
  - origin: docker.io/adoptopenjdk/openjdk11
    transfer: registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_adoptopenjdk_openjdk11
    private: docker-hosted.nstl-dev.com/adoptopenjdk/openjdk11
build:
  - origin: registry.cn-beijing.aliyuncs.com/public-image-mirror/docker.io_jetbrains_teamcity-agent
    private: docker-hosted.nstl-dev.com/jetbrains/teamcity-agent