name: GitHub Actions Build Images
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    branches:
      - main
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
jobs:
  build-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-build-images
      cancel-in-progress: true
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_EARTHLY_TOKEN }}
          version: "latest" # or pin to an specific version, e.g. "0.8.1"
      - uses: actions/checkout@v2
      - name: Docker login # to avoid dockerhub rate-limiting
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: what version is installed?
        run: earthly --version
      - name: run the earthly hello world
        run: earthly github.com/earthly/hello-world:main+hello