name: GitHub Actions Build Images For Sync
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    paths:
      - Earthfile
      - .github/workflows/build-images-sync.yml
    branches:
      - main
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
jobs:
  build-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-build-images-sync
      cancel-in-progress: true
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_EARTHLY_TOKEN }}
          version: "latest" # or pin to an specific version, e.g. "0.8.1"
      - uses: actions/checkout@v2
      - name: Docker login # to avoid dockerhub rate-limiting
        run: docker login --username "${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME }}" --password "${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD }}" registry.cn-beijing.aliyuncs.com/public-image-mirror
      - name: what version is installed?
        run: earthly --version
      - name: build images
        run: earthly --ci --push +sync