name: GitHub Actions Sync Repository
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    paths-ignore:
      - generate/images.yaml
    branches:
      - main

jobs:
  sync-repository:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-sync-repository
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install PyYAML
        run: pip install pyyaml
      - name: generate images.yaml
        run: python main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Action"
          author_email: action@example.com
          message: 'Generated generate/images.yaml'
          add: 'generate/images.yaml'
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/NstlDev
          dst: gitee/NstlDev
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          static_list: "public-image-syncer"
          # src_account_type: org
          # dst_account_type: org