name: GitHub Actions Sync Repository
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    branches:
      - main

jobs:
  sync-repository:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-sync-repository
      cancel-in-progress: true
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install PyYAML
        run: pip install pyyaml
      - name: generate images.yaml
        run: python main.py
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: ossutil cp -f images.yaml oss://${{ secrets.OSS_BUCKET }}/
      - run: ossutil ls oss://${{ secrets.OSS_BUCKET }}
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: github/NstlDev
          dst: gitee/NstlDev
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          static_list: "public-image-syncer"
          # src_account_type: org
          # dst_account_type: org