name: Target Sync Image For Issue
on:
  issues:
    types:
      - opened

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'sync image')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
      issues: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Issue
        id: get-image
        env:
          IMAGE: "${{ github.event.issue.title }}"
        run: |
          chmod +x ./hack/correct-image.sh ./hack/verify-allows.sh
          # 生成allows.txt
          python hack/generate_allow.py
          
          ORIGIN_IMAGE="${IMAGE}"
          CORRECT_IMAGE="$(./hack/correct-image.sh "${ORIGIN_IMAGE}")"
          if [[ "${CORRECT_IMAGE}" == "" ]]; then
            gh issue comment ${{ github.event.issue.number }} -b "镜像 '${ORIGIN_IMAGE}' 不是一个镜像"
            exit 1
          fi
          
          # 镜像格式检测
          if [[ "${CORRECT_IMAGE}" != "${ORIGIN_IMAGE}" ]]; then
              gh issue comment ${{ github.event.issue.number }} -b "镜像 '${ORIGIN_IMAGE}' 不存在呢, 也许应该是 '${CORRECT_IMAGE}'"
            exit 1
          fi
          
          # 镜像白名单检测
          if ! ./hack/verify-allows.sh ./allows.txt "${ORIGIN_IMAGE}"; then
            gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 不在允许列表中, 不支持同步和访问"
            exit 1
          fi
          
          echo "image=${ORIGIN_IMAGE}" >> $GITHUB_OUTPUT

      - name: Check Image
        run: |
          ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
          gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步中...<br>[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

      - name: Generate Image yaml
        run: |
          python hack/generate_issue_images.py ${{ github.event.issue.number }} ${{ steps.get-image.outputs.image }}
          cat issue_images.yaml
          cat target_images_${{ github.event.issue.number }}.yaml

      - name: Image Sync Action
        uses: NstlDev/image-sync-action@v1.1.2
        with:
          auth_file: ./config/auth.yaml
          images_file: ./issue_images.yaml
          version: latest
          proc: 10
          # stderr 重定向至 stdout
          append_script: '2>&1 | grep -v "Auth information not found" | grep -v "Finish synchronizing blob sha256:"'
        env:
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME }}
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD }}

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: ossutil cp -f target_images_${{ github.event.issue.number }}.yaml oss://${{ secrets.OSS_BUCKET }}/
      - run: ossutil ls oss://${{ secrets.OSS_BUCKET }}
      # 获取接收文件
      - run: |
          OSS_BUCKET=${{ secrets.OSS_BUCKET }}
          ISSUE_NUMBER=${{ github.event.issue.number }}
          # Function to check if the target file exists
          check_file() {
            ossutil ls oss://${OSS_BUCKET} | grep received_target_images_${ISSUE_NUMBER}.yaml
          }
          # Loop to check if the file exists
          start_time=$(date +%s)
          timeout=300
          while [[ $(($(date +%s) - start_time)) -lt $timeout ]]; do
            if check_file; then
              echo "File found, exiting loop"
              break
            else
              echo "File not found, waiting 30 seconds before trying again"
              sleep 30
            fi
          done
          # Check if file was found or not
          if check_file; then
            echo "File successfully retrieved"
            ossutil rm -f oss://${OSS_BUCKET}/received_target_images_${ISSUE_NUMBER}.yaml
          else
            echo "File not found within $timeout seconds, retrieval failed"
            gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 私服接收超时, 超时时间: $timeout seconds"
            ossutil rm -f oss://${OSS_BUCKET}/received_target_images_${ISSUE_NUMBER}.yaml
            exit 1
          fi
      # 获取状态文件
      - run: |
          OSS_BUCKET=${{ secrets.OSS_BUCKET }}
          ISSUE_NUMBER=${{ github.event.issue.number }}
          # Function to check if the target file exists
          check_file_failed() {
            ossutil ls oss://${OSS_BUCKET} | grep failed_target_images_${ISSUE_NUMBER}.yaml
          }
          check_file_success() {
            ossutil ls oss://${OSS_BUCKET} | grep success_target_images_${ISSUE_NUMBER}.yaml
          }
          # Loop to check if the file exists
          start_time=$(date +%s)
          timeout=600
          while [[ $(($(date +%s) - start_time)) -lt $timeout ]]; do
            if check_file_success||check_file_failed; then
              echo "File found, exiting loop"
              break
            else
              echo "File not found, waiting 30 seconds before trying again"
              sleep 30
            fi
          done
          
          
          # Check if file was found or not
          if check_file_success||check_file_failed; then
            if check_file_failed; then
              echo "执行失败"
              ossutil rm -f oss://${OSS_BUCKET}/failed_target_images_${ISSUE_NUMBER}.yaml
              exit 1
            else
              echo "执行成功"
              ossutil rm -f oss://${OSS_BUCKET}/success_target_images_${ISSUE_NUMBER}.yaml
            fi
          else
            echo "File not found within $timeout seconds, retrieval failed"
            gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 私服同步超时, 超时时间: $timeout seconds"
            exit 1
          fi

      - name: Sync Images
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步完成"
          gh issue edit ${{ github.event.issue.number }} --add-label "sync image succeeded" -b "IMAGE SYNC"
          gh issue close ${{ github.event.issue.number }} --reason "completed"

      - name: Fail Sync
        if: failure()
        run: |
          ORIGIN_IMAGE="${{ steps.get-image.outputs.image }}"
          gh issue comment ${{ github.event.issue.number }} -b "镜像 ${ORIGIN_IMAGE} 同步失败[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})<br>请检查镜像是否存在以及在白名单, [查看成功例子](https://github.com/${{ github.repository }}/issues?q=is%3Aissue+is%3Aclosed+label%3A%22sync+image+succeeded%22)<br>如有疑问请回复 /auto-cc 召唤帮助"
          gh issue edit ${{ github.event.issue.number }} --add-label "sync image failure" -b "IMAGE SYNC"
          gh issue close ${{ github.event.issue.number }} --reason "not planned"