name: GitHub Actions Sync Repository
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    branches:
      - main

jobs:
  sync-repository:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-sync-repository
      cancel-in-progress: true
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate images.yaml
        run: |
          python hack/generate_images.py
          
          echo "---------------------------------------transfer-images.yaml"
          cat transfer-images.yaml
          
          echo ""
          echo "---------------------------------------private-images.yaml"
          cat private-images.yaml

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: |
          ossutil cp -f transfer-images.yaml oss://${{ secrets.OSS_BUCKET }}/
          ossutil cp -f private-images.yaml oss://${{ secrets.OSS_BUCKET }}/
          ossutil ls oss://${{ secrets.OSS_BUCKET }}

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: github/n-devops
          dst: gitee/n-devops
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          static_list: "public-image-syncer"
          # src_account_type: org
          # dst_account_type: org