name: GitHub Actions Sync Images
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    branches:
      - main
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
jobs:
  sync-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-sync-images
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Image Sync Action
        uses: NstlDev/image-sync-action@v1.1.2
        with:
          auth_file: ./config/auth.yaml
          images_file: ./config/images.yaml
          version: latest
          proc: 10
          # stderr 重定向至 stdout
          append_script: '2>&1 | grep -v "Auth information not found" | grep -v "Finish synchronizing blob sha256:"'
        env:
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME }}
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD }}
