name: GitHub Actions Sync Images For Schedule
on:
  # 手动触发
  workflow_dispatch:
  # push触发
  push:
    paths:
      - .github/workflows/sync-images-for-schedule.yml
      - config/transfer-images.yaml
      - config/image-mappings.yaml
    branches:
      - main
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"
jobs:
  sync-images:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-sync-images
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: generate images.yaml
        run: |
          python hack/generate_images.py
          
          echo "---------------------------------------transfer-images.yaml"
          cat transfer-images.yaml
          
          echo ""
          echo "---------------------------------------private-images.yaml"
          cat private-images.yaml

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - run: |
          ossutil cp -f transfer-images.yaml oss://${{ secrets.OSS_BUCKET }}/
          ossutil cp -f private-images.yaml oss://${{ secrets.OSS_BUCKET }}/
          ossutil ls oss://${{ secrets.OSS_BUCKET }}

      - name: Image Sync Action
        uses: NstlDev/image-sync-action@v1.1.2
        with:
          auth_file: ./config/auth.yaml
          images_file: transfer-images.yaml
          version: latest
          proc: 10
          # stderr 重定向至 stdout
          append_script: '2>&1 | grep -v "Auth information not found" | grep -v "Finish synchronizing blob sha256:"'
        env:
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_USERNAME }}
          ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD: ${{ secrets.ALIYUNCS_BEIJING_PUBLIC_IMAGE_MIRROR_PASSWORD }}
